### PR TITLE
Added Darwin Core Terms vocab

### LINKED ISSUE #35: Attempting to add Darwin Core vocabulary - error
Hi, we are attempting to add Darwin Core metadata for a Hydra project we are working on here at Indiana University.  My addition to the vocab.yml file is as follows:

dwc:
  class_name: DWC
  uri: http://rs.tdwg.org/dwc/terms/
  source: http://rs.tdwg.org/dwc/rdf/dwcterms.rdf

The error when running the rake task to generate the DWC vocab file is: "root must be a proxy not a NilClass". I'm sure I'm just missing something fundamental here but I'm not sure what it is.

### PR DESCRIPTION
**Pull request by dchandekstark**
Source file was downloaded from http://rs.tdwg.org/dwc/rdf/dwcterms.rdf
and converted to UTF-8 encoding, which fixes #35.

The config file now permits source to be a file path relative to the
new sources/ directory in the root of the project.

/cc @jhallida @acoburn

### CODE REVIEW

**Comment by dchandekstark** [comment]
If this is merged the config file comments should be updated to reflect the relative file path option for source.  Also, there isn't a spec test.

**Comment by jhallida** [comment]
Thanks! I had no idea I would open this particular can of worms but I'm happy to see it getting resolved so quickly.

**Comment by dchandekstark** [comment]
@acoburn submitted a patch to the DWC folks which was accepted, although we don't know when they will release it as a replacement of the current file. Meanwhile, we could release this version and update it when DWC publishes the fixed version.

**Comment by acoburn** [comment]
I'm +1 to merging this PR.

The current DWC vocabulary was published Nov 8, 2014, and the previous version was published Oct 22, 2013. I doubt that removing three invisible bytes from a file will lead them to publish a new version anytime soon.

**Comment by dchandekstark** [comment]
@acoburn In the spirit of not merging one's own requests, please merge. :smile:

**Pull request merged**
